### ISSUE TITLE
Apply job form

### ISSUE THREAD

**Issue by Mehonoshin** [symbiod/juniorjobs#79]
JobApplication Model
Form(email, message, github profile, linkedin, moirkrug links, CV file)
Controller action

Идея в том, чтобы кандидат не связывался с компанией напрямую, а заполнял форму у нас и мы пересылали это на email компании.
На rubyjobs происходит также.

**Comment by dborovsky** [comment]
без модерации
просто мы сохраняем отклик к себе в базу
+ captcha
